### ISSUE TITLE
Question: Is it compatible with PHP 8.1+?

### ISSUE THREAD

**Issue by aleckyann** [yidas/codeigniter-worker#10]
A good amount of things have changed in php 8 and I still haven't been able to tackle them with your work.

**Comment by yidas** [comment]
Hi @aleckyann,

Regarding PHP 8 migration document, I think that there is no impact of the library compatibility:
https://www.php.net/manual/en/migration80.deprecated.php

In addition, it seems that Codeigniter 3.x is running successfully with PHP 8.0 as well:
https://forum.codeigniter.com/thread-78091.html

Best regards

**Comment by aleckyann** [comment]
I did some tests, so far everything seems to work perfectly in php 8.1. Thank you very much for your work @yidas !
