### ISSUE TITLE
Trying to understand how things work & how it should be used

### ISSUE THREAD

**Issue by amiraiman** [yidas/codeigniter-worker#11]
From my understanding, you only need to run `php index.php worker listen` and the listener will automatically dispatch a worker if there's a job in the queue (given that you configured everything as described in the README). `php index.php worker work` is used to run the worker manually while `php index.php worker launch` is used to run the listener in the background.

Is my assumptions right and if it is, is the following practice correct:
 - In production I will only need to set one cron job to run the command `php index.php worker launch`
 - Then whenever I want to add a job to my queue, I can simply dispatch a job to my configured queue with my own library
 - The listener will automatically detects a new job in the queue & dispatch a worker
 - Worker will handle the job & remove it from the queue upon completion

**Comment by yidas** [comment]
Hi @amiraiman,

Yes, your understanding is right!

Cheers

**Comment by amiraiman** [comment]
Hi @yidas,

Thanks for this library!

I will close this issue now.
