### ISSUE TITLE
where i can find library('myjobs');

### ISSUE THREAD

**Issue by gietmxh** [yidas/codeigniter-worker#2]
$this->load->library('myjobs');

**Comment by yidas** [comment]
`myjobs` library is an example for defining by your own in your application which handles your job processes.

**Comment by gietmxh** [comment]
@yidas  do you have example code.

**Comment by yidas** [comment]
As you wish, the whole example included own application job process will be released in the future.

**Comment by gietmxh** [comment]
@yidas can you released it in this afternoon . Or can you suggest me some projects has the same function

**Comment by yidas** [comment]
@gietmxh 

You need to design the job queue by your own, you can implement it by using memcache or database.

For database suggestion, you could launch worker after finishing the process for handling jobs in database.
