### ISSUE TITLE
Listener not running

### ISSUE THREAD

**Issue by adeelpervaiz** [yidas/codeigniter-worker#4]
I did setup everything was working fine.
There were some health issues coming so I did kill by PID.
Now when I run this command.
php index.php MyWorker/launch

It does not start listening, and this commands is printing only.

`ps aux|grep php

root      2132  0.0  2.7 451296 27964 ?        Ss   14:42   0:00 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)

www-data  2160  0.0  1.5 453596 15856 ?        S    14:42   0:00 php-fpm: pool www

www-data  2161  0.0  1.5 453596 15856 ?        S    14:42   0:00 php-fpm: pool www

ubuntu    2709  0.0  0.1  14856  1032 pts/0    S+   15:59   0:00 grep --color=auto php`

Adeel

**Comment by yidas** [comment]
Is this the result after `php index.php MyWorker/launch` command?

> `ps aux|grep php
>
> root 2132 0.0 2.7 451296 27964 ? Ss 14:42 0:00 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)...

**Comment by adeelpervaiz** [comment]
Yes

**Comment by yidas** [comment]
@adeelpervaiz,

No such problem.

You can check if you follow the instructions to install and config.
