### ISSUE TITLE
Question: Compatible Codeigniter V2?

### ISSUE THREAD

**Issue by sefirosweb** [yidas/codeigniter-worker#7]
Hello, I saw in documentation is requeried codeigniter version 3+

It is possible to make compatible with version 2?

Another question, you can store data for use it in the queue job? similar has laravel?

**Comment by yidas** [comment]
Hi @sefirosweb,

Unfortunately, this package only used for codeigniter version 3.X.
Each major release of Codeigniter has huge compatibility gap.

For another question, yes, you can store queue data in a queue and pop it to use.
This part needs to be implemented by your own.

Best regards
